<?php

declare(strict_types=1);

use App\Models\AvailabilitySlot;
use App\Models\Service;
use App\Models\User;
use Illuminate\Support\Facades\Hash;

require __DIR__ . '/../vendor/autoload.php';

$app = require __DIR__ . '/../bootstrap/app.php';
$app->make(Illuminate\Contracts\Console\Kernel::class)->bootstrap();

$imagePool = [
    '/storage/services/7867b513-3d14-4f76-9560-021eb52ef608.jpg',
    '/storage/services/80dbd0db-1358-458e-9854-34d6e52567f0.jpg',
    '/storage/services/e6833b61-4340-41f5-abc2-50633b460ca3.jpg',
    '/storage/services/ff913be2-60da-4887-a9f4-a489f0ec7bfb.jpg',
    '/storage/services/3923033e-6531-4c24-a67e-51c65536db22.png',
    '/storage/services/6f735541-745e-448d-8655-8c460cb698c7.png',
];

$partnerOne = User::query()->updateOrCreate(
    ['email' => 'partner.demo1@wandireo.com'],
    [
        'name' => 'Atlantic Motion',
        'email_verified_at' => now(),
        'password' => Hash::make('PartnerDemo2026!'),
        'role' => 'PARTNER',
        'first_name' => 'Atlantic',
        'last_name' => 'Motion',
        'language' => 'fr',
        'company_name' => 'Atlantic Motion',
        'partner_status' => 'APPROVED',
        'commission_rate' => 0.18,
    ],
);

$partnerTwo = User::query()->updateOrCreate(
    ['email' => 'partner.demo2@wandireo.com'],
    [
        'name' => 'Blue Horizon Rentals',
        'email_verified_at' => now(),
        'password' => Hash::make('PartnerDemo2026!'),
        'role' => 'PARTNER',
        'first_name' => 'Blue',
        'last_name' => 'Horizon',
        'language' => 'en',
        'company_name' => 'Blue Horizon Rentals',
        'partner_status' => 'APPROVED',
        'commission_rate' => 0.20,
    ],
);

$services = [
    [
        'title' => 'Range Rover Sport Algarve',
        'partner' => $partnerOne,
        'category' => 'VOITURE',
        'pricing_unit' => 'PAR_JOUR',
        'partner_price' => 165,
        'payment_mode' => 'FULL_ONLINE',
        'booking_mode' => 'INSTANT',
        'city' => 'Faro',
        'country' => 'Portugal',
        'region' => 'Algarve',
        'latitude' => 37.0194,
        'longitude' => -7.9304,
        'description' => 'SUV premium ideal pour les transferts, week-ends et sejours haut de gamme en Algarve. Livraison possible a l aeroport de Faro.',
        'images' => [$imagePool[0], $imagePool[1], $imagePool[4]],
        'tags' => ['suv', 'premium', 'aeroport', 'automatique'],
        'extra_data' => [
            'vehicleType' => 'SUV',
            'brand' => 'Land Rover',
            'model' => 'Range Rover Sport',
            'year' => 2024,
            'transmission' => 'AUTOMATIQUE',
            'fuelType' => 'HYBRIDE',
            'seats' => 5,
            'doors' => 5,
            'airConditioning' => true,
            'driverMinAge' => 25,
            'driverLicenseYearsRequired' => 3,
            'fuelIncluded' => false,
            'mileageLimit' => 'ILLIMITE',
            'insuranceIncluded' => true,
            'depositAmountEur' => 1800,
            'deliveryAvailable' => true,
            'deliveryLocations' => ['Aeroport de Faro', 'Vilamoura', 'Albufeira'],
            'additionalDriverAllowed' => true,
            'additionalDriverFeePerDay' => 18,
            'pickupLocations' => ['Faro', 'Vilamoura'],
            'luggage' => ['smallBags' => 3, 'largeSuitcases' => 3],
        ],
        'availability' => 'range',
    ],
    [
        'title' => 'Mercedes Classe A Lagos',
        'partner' => $partnerTwo,
        'category' => 'VOITURE',
        'pricing_unit' => 'PAR_JOUR',
        'partner_price' => 78,
        'payment_mode' => 'COMMISSION_ONLINE_REST_ON_SITE',
        'booking_mode' => 'REQUEST',
        'city' => 'Lagos',
        'country' => 'Portugal',
        'region' => 'Algarve',
        'latitude' => 37.1028,
        'longitude' => -8.6742,
        'description' => 'Berline compacte premium, parfaite pour explorer Lagos et toute la cote sud avec confort et faible consommation.',
        'images' => [$imagePool[1], $imagePool[5], $imagePool[2]],
        'tags' => ['berline', 'compacte', 'lagos', 'premium'],
        'extra_data' => [
            'vehicleType' => 'BERLINE',
            'brand' => 'Mercedes-Benz',
            'model' => 'Classe A',
            'year' => 2023,
            'transmission' => 'AUTOMATIQUE',
            'fuelType' => 'ESSENCE',
            'seats' => 5,
            'doors' => 5,
            'airConditioning' => true,
            'driverMinAge' => 23,
            'driverLicenseYearsRequired' => 2,
            'fuelIncluded' => false,
            'mileageLimit' => 250,
            'mileageExtraChargePerKm' => 0.35,
            'insuranceIncluded' => true,
            'depositAmountEur' => 900,
            'deliveryAvailable' => true,
            'deliveryLocations' => ['Lagos Marina', 'Praia da Luz'],
            'additionalDriverAllowed' => true,
            'additionalDriverFeePerDay' => 12,
            'pickupLocations' => ['Lagos'],
            'luggage' => ['smallBags' => 2, 'largeSuitcases' => 2],
        ],
        'availability' => 'range',
    ],
    [
        'title' => 'Catamaran Sunset Ponta da Piedade',
        'partner' => $partnerOne,
        'category' => 'BATEAU',
        'pricing_unit' => 'PAR_DEMI_JOURNEE',
        'partner_price' => 420,
        'payment_mode' => 'FULL_ONLINE',
        'booking_mode' => 'REQUEST',
        'city' => 'Lagos',
        'country' => 'Portugal',
        'region' => 'Algarve',
        'latitude' => 37.0918,
        'longitude' => -8.6680,
        'description' => 'Catamaran prive pour croisiere sunset avec equipage, boissons et itineraire vers les grottes et falaises de Ponta da Piedade.',
        'images' => [$imagePool[2], $imagePool[3], $imagePool[0]],
        'tags' => ['catamaran', 'sunset', 'skipper', 'premium'],
        'extra_data' => [
            'boatType' => 'CATAMARAN',
            'boatName' => 'Sunset Pearl',
            'passengerCapacity' => 12,
            'sleepingBerths' => 6,
            'lengthMeters' => 13.4,
            'manufactureYear' => 2022,
            'engineType' => 'VOILE_ET_MOTEUR',
            'enginePowerKw' => 55,
            'rentalMode' => 'AVEC_SKIPPER',
            'cabins' => 4,
            'bathrooms' => 2,
            'amenities' => ['Bluetooth', 'Douche de pont', 'Paddle', 'Bar lounge'],
            'navigationArea' => ['Lagos', 'Benagil', 'Ponta da Piedade'],
            'licenseRequired' => false,
            'fuelIncluded' => true,
            'depositAmountEur' => 2500,
            'insuranceIncluded' => true,
            'departurePorts' => ['Marina de Lagos'],
            'availableForDayCharter' => true,
            'availableForWeekCharter' => false,
        ],
        'availability' => 'range',
    ],
    [
        'title' => 'Yacht Prestige Vilamoura',
        'partner' => $partnerTwo,
        'category' => 'BATEAU',
        'pricing_unit' => 'PAR_JOUR',
        'partner_price' => 950,
        'payment_mode' => 'CONNECTED_ACCOUNT',
        'booking_mode' => 'REQUEST',
        'city' => 'Vilamoura',
        'country' => 'Portugal',
        'region' => 'Algarve',
        'latitude' => 37.0775,
        'longitude' => -8.1180,
        'description' => 'Yacht moteur premium avec equipage complet, ideal pour day charter, celebrations privees et sorties corporate.',
        'images' => [$imagePool[3], $imagePool[2], $imagePool[5]],
        'tags' => ['yacht', 'vilamoura', 'luxe', 'equipage'],
        'extra_data' => [
            'boatType' => 'YACHT_MOTEUR',
            'boatName' => 'Prestige Azure',
            'passengerCapacity' => 10,
            'sleepingBerths' => 4,
            'lengthMeters' => 15.8,
            'manufactureYear' => 2021,
            'engineType' => 'MOTEUR',
            'enginePowerKw' => 130,
            'rentalMode' => 'AVEC_EQUIPAGE_COMPLET',
            'cabins' => 3,
            'bathrooms' => 2,
            'amenities' => ['Flybridge', 'Snorkeling', 'Champagne setup', 'Seabob'],
            'navigationArea' => ['Vilamoura', 'Albufeira', 'Benagil'],
            'licenseRequired' => false,
            'fuelIncluded' => true,
            'depositAmountEur' => 4000,
            'insuranceIncluded' => true,
            'departurePorts' => ['Marina de Vilamoura'],
            'availableForDayCharter' => true,
            'availableForWeekCharter' => false,
        ],
        'availability' => 'range',
    ],
    [
        'title' => 'Villa Ocean View Albufeira',
        'partner' => $partnerOne,
        'category' => 'HEBERGEMENT',
        'pricing_unit' => 'PAR_NUIT',
        'partner_price' => 285,
        'payment_mode' => 'FULL_ONLINE',
        'booking_mode' => 'INSTANT',
        'city' => 'Albufeira',
        'country' => 'Portugal',
        'region' => 'Algarve',
        'latitude' => 37.0891,
        'longitude' => -8.2479,
        'description' => 'Villa premium avec piscine privee, vue mer et grande terrasse. Parfaite pour familles et groupes recherchant calme et design contemporain.',
        'images' => [$imagePool[4], $imagePool[0], $imagePool[1]],
        'tags' => ['villa', 'piscine', 'vue mer', 'famille'],
        'extra_data' => [
            'accommodationType' => 'VILLA',
            'starRating' => 5,
            'maxGuests' => 8,
            'bedrooms' => 4,
            'bathrooms' => 3,
            'totalSurfaceM2' => 220,
            'amenities' => ['WiFi', 'Piscine', 'Cuisine equipee', 'Barbecue', 'Parking'],
            'checkInTime' => '16:00',
            'checkOutTime' => '11:00',
            'breakfastIncluded' => false,
            'minimumStayNights' => 2,
            'petsAllowed' => false,
            'smokingAllowed' => false,
            'accessibilityFeatures' => ['Acces plain-pied'],
            'houseRules' => ['Pas de fetes', 'Respect du voisinage'],
            'cancellationPolicy' => 'MODEREE',
            'nearbyAttractions' => ['Praia da Oura', 'Old Town Albufeira'],
            'distanceToBeachMeters' => 850,
            'distanceToCityKm' => 2.5,
        ],
        'availability' => 'range',
    ],
    [
        'title' => 'Suite Marina Faro Boutique Stay',
        'partner' => $partnerTwo,
        'category' => 'HEBERGEMENT',
        'pricing_unit' => 'PAR_NUIT',
        'partner_price' => 138,
        'payment_mode' => 'COMMISSION_ONLINE_REST_ON_SITE',
        'booking_mode' => 'REQUEST',
        'city' => 'Faro',
        'country' => 'Portugal',
        'region' => 'Algarve',
        'latitude' => 37.0154,
        'longitude' => -7.9353,
        'description' => 'Suite boutique au coeur de Faro, entre marina et vieille ville, avec design mediterraneen, rooftop et service conciergerie.',
        'images' => [$imagePool[5], $imagePool[4], $imagePool[3]],
        'tags' => ['suite', 'boutique', 'marina', 'city break'],
        'extra_data' => [
            'accommodationType' => 'HOTEL',
            'starRating' => 4,
            'maxGuests' => 2,
            'bedrooms' => 1,
            'bathrooms' => 1,
            'totalSurfaceM2' => 38,
            'amenities' => ['WiFi', 'Climatisation', 'Petit-dejeuner', 'Rooftop'],
            'checkInTime' => '15:00',
            'checkOutTime' => '12:00',
            'breakfastIncluded' => true,
            'minimumStayNights' => 1,
            'petsAllowed' => false,
            'smokingAllowed' => false,
            'accessibilityFeatures' => ['Ascenseur'],
            'houseRules' => ['Check-in avec passeport'],
            'cancellationPolicy' => 'FLEXIBLE',
            'nearbyAttractions' => ['Marina de Faro', 'Cidade Velha'],
            'distanceToBeachMeters' => 5500,
            'distanceToCityKm' => 0.4,
        ],
        'availability' => 'range',
    ],
];

foreach ($services as $index => $definition) {
    $service = Service::query()->updateOrCreate(
        ['title' => $definition['title']],
        [
            'partner_id' => $definition['partner']->id,
            'description' => $definition['description'],
            'category' => $definition['category'],
            'location_city' => $definition['city'],
            'location_country' => $definition['country'],
            'location_region' => $definition['region'],
            'location_latitude' => $definition['latitude'],
            'location_longitude' => $definition['longitude'],
            'images' => $definition['images'],
            'pricing_unit' => $definition['pricing_unit'],
            'partner_price' => $definition['partner_price'],
            'commission_rate' => $definition['partner']->commission_rate ?? 0.20,
            'currency' => 'EUR',
            'payment_mode' => $definition['payment_mode'],
            'booking_mode' => $definition['booking_mode'],
            'featured' => $index < 3,
            'rating' => null,
            'review_count' => 0,
            'is_available' => true,
            'tags' => $definition['tags'],
            'extra_data' => $definition['extra_data'],
            'source_type' => 'LOCAL',
        ],
    );

    if ($definition['availability'] === 'range') {
        for ($day = 2; $day <= 18; $day++) {
            $date = now()->addDays($day)->toDateString();

            AvailabilitySlot::query()->updateOrCreate(
                [
                    'service_id' => $service->id,
                    'date' => $date,
                ],
                [
                    'source_type' => 'MANUAL',
                    'is_blocked' => false,
                    'slots' => $service->category === 'HEBERGEMENT'
                        || $service->category === 'BATEAU'
                        || $service->category === 'VOITURE'
                        ? [['startTime' => '09:00', 'maxCapacity' => 1]]
                        : [['startTime' => '09:00', 'maxCapacity' => 8]],
                ],
            );
        }
    }
}

echo json_encode([
    'partners' => User::query()->where('role', 'PARTNER')->count(),
    'services_by_category' => Service::query()
        ->selectRaw('category, count(*) as total')
        ->groupBy('category')
        ->pluck('total', 'category'),
], JSON_PRETTY_PRINT | JSON_UNESCAPED_UNICODE);
